from __future__ import annotations

from typing import Any


RIGHT_MODULES = {
    "tenant": "Tenant Rights",
    "employment": "Employment Rights",
    "consumer": "Consumer Complaint Rights",
    "cyber": "Cyber Crime Rights",
    "women": "Women Protection Rights",
    "senior": "Senior Citizen Rights",
    "rti": "RTI Rights",
}


class RightsEligibilityEngine:
    def evaluate(self, domain: str, facts: dict[str, Any]) -> dict[str, Any]:
        normalized = domain.lower().strip()
        if normalized not in RIGHT_MODULES:
            normalized = self._infer_domain(facts)
        rules = getattr(self, f"_rules_{normalized}", self._rules_general)
        rights = rules(facts)
        applied_count = sum(1 for right in rights if right["applies"])
        confidence = 0.55 + min(0.35, applied_count * 0.08)
        return {
            "domain": normalized,
            "module": RIGHT_MODULES.get(normalized, "General Rights"),
            "rights": rights,
            "missing_facts": self._missing_facts(normalized, facts),
            "confidence": round(confidence, 2),
            "explainability": "Each right is generated by deterministic rules and includes its source note.",
        }

    def _infer_domain(self, facts: dict[str, Any]) -> str:
        text = " ".join(str(value).lower() for value in facts.values())
        for domain in RIGHT_MODULES:
            if domain in text:
                return domain
        return "tenant"

    def _rules_tenant(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        months = int(facts.get("tenant_months", 0) or 0)
        eviction_notice = bool(facts.get("eviction_notice_received", False))
        deposit_withheld = bool(facts.get("deposit_withheld", False))
        repair_issue = bool(facts.get("repair_issue", False))
        rights = [
            self._right(
                "Quiet enjoyment",
                "A tenant should usually be able to use the rented home without improper interference.",
                "Tenant Rights Module: quiet enjoyment note",
                True,
            )
        ]
        if months >= 12 or eviction_notice:
            rights.append(
                self._right(
                    "Notice before eviction",
                    "Ask for written notice and check whether the lease or local rent law requires a minimum notice period.",
                    "Tenant Rights Module: eviction notice rule",
                    True,
                )
            )
        if deposit_withheld:
            rights.append(
                self._right(
                    "Deposit explanation",
                    "You can ask for an itemized explanation for deductions from the security deposit.",
                    "Tenant Rights Module: security deposit rule",
                    True,
                )
            )
        if repair_issue:
            rights.append(
                self._right(
                    "Repair record",
                    "Keep dated repair requests and responses; essential habitability issues should be documented.",
                    "Tenant Rights Module: repair documentation rule",
                    True,
                )
            )
        return rights

    def _rules_employment(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        terminated = bool(facts.get("terminated", False))
        unpaid_wages = bool(facts.get("unpaid_wages", False))
        return [
            self._right("Written employment terms", "Keep offer letters, salary slips, and policy documents.", "Employment Module: records rule", True),
            self._right("Unpaid wage claim", "If wages are unpaid, preserve attendance, payslips, and bank records.", "Employment Module: wage rule", unpaid_wages),
            self._right("Termination review", "If terminated, review notice, reason, and final settlement terms.", "Employment Module: termination rule", terminated),
        ]

    def _rules_consumer(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        defect = bool(facts.get("defective_product", False))
        service_issue = bool(facts.get("service_deficiency", False))
        return [
            self._right("Proof of purchase", "Keep invoice, warranty, screenshots, and complaint records.", "Consumer Module: evidence rule", True),
            self._right("Defect complaint", "For defective goods, request repair, replacement, refund, or compensation as applicable.", "Consumer Module: defect rule", defect),
            self._right("Service deficiency complaint", "For poor services, preserve communication and escalation records.", "Consumer Module: service rule", service_issue),
        ]

    def _rules_cyber(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        money_lost = bool(facts.get("money_lost", False))
        return [
            self._right("Preserve digital evidence", "Save URLs, screenshots, transaction IDs, phone numbers, and emails.", "Cyber Module: evidence rule", True),
            self._right("Report quickly", "For financial cyber fraud, report quickly to improve recovery chances.", "Cyber Module: urgent reporting rule", money_lost),
        ]

    def _rules_women(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        harassment = bool(facts.get("harassment", False))
        domestic_violence = bool(facts.get("domestic_violence", False))
        return [
            self._right("Safety planning", "Prioritize immediate safety and preserve evidence without confronting the accused alone.", "Women Protection Module: safety rule", True),
            self._right("Workplace harassment process", "Workplace sexual harassment complaints may involve an Internal Committee process.", "Women Protection Module: workplace rule", harassment),
            self._right("Protection support", "Domestic violence situations may involve protection, residence, and maintenance-related remedies.", "Women Protection Module: domestic violence rule", domestic_violence),
        ]

    def _rules_senior(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        maintenance_needed = bool(facts.get("maintenance_needed", False))
        abuse = bool(facts.get("abuse", False))
        return [
            self._right("Maintenance support", "Senior citizens may seek maintenance support from children or legal heirs in qualifying situations.", "Senior Citizen Module: maintenance rule", maintenance_needed),
            self._right("Protection from abuse", "Document abuse, neglect, or property pressure and seek local authority support.", "Senior Citizen Module: protection rule", abuse),
        ]

    def _rules_rti(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        govt_info = bool(facts.get("government_information", False))
        return [
            self._right("Information request", "RTI is for information held by public authorities, not private disputes by itself.", "RTI Module: public authority rule", govt_info),
            self._right("Appeal path", "If no response or an unsatisfactory response is received, note dates for appeal timelines.", "RTI Module: appeal rule", True),
        ]

    def _rules_general(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        return [self._right("Document everything", "Keep dates, documents, screenshots, notices, receipts, and witness details.", "General Rights Module", True)]

    def _right(self, title: str, explanation: str, source: str, applies: bool) -> dict[str, Any]:
        return {
            "title": title,
            "applies": applies,
            "explanation": explanation,
            "source": source,
        }

    def _missing_facts(self, domain: str, facts: dict[str, Any]) -> list[str]:
        expected = {
            "tenant": ["tenant_months", "eviction_notice_received", "deposit_withheld", "repair_issue"],
            "employment": ["terminated", "unpaid_wages"],
            "consumer": ["defective_product", "service_deficiency"],
            "cyber": ["money_lost"],
            "women": ["harassment", "domestic_violence"],
            "senior": ["maintenance_needed", "abuse"],
            "rti": ["government_information"],
        }.get(domain, [])
        return [key for key in expected if key not in facts]
